OVERWRITE_LOG = True
IMMEDIATE_COMPUTE = True
CHECK_VALIDITY = True
RESOURCE_WARNINGS = True
LOG_LEVEL_CONSOLE = "DEBUG"
LOG_LEVEL_FILE = "DEBUG"
DEFAULT_MOD_PATH = "{EXP_DIR}/models/{EXP}.mod"
DEFAULT_LOG_PATH = "{EXP_DIR}/logs/{EXP}.log"
