OVERWRITE_LOG = True
IMMEDIATE_COMPUTE = False
CHECK_VALIDITY = False
RESOURCE_WARNINGS = True
LOG_LEVEL_CONSOLE = "WARNING"
LOG_LEVEL_FILE = "DEBUG"
DEFAULT_MOD_PATH = "{EXP_DIR}/models/{EXP}.mod"
DEFAULT_LOG_PATH = "{EXP_DIR}/logs/{EXP}.log"
