# This demonstrates using a sequence classifier model that takes a sequence as input and outputs a single class label.
classifier: !Experiment
  model: !SequenceClassifier
    src_reader: !PlainTextReader
      vocab: !Vocab {vocab_file: examples/data/head.en.vocab}
    trg_reader: !IDReader {}
    src_embedder: !SimpleWordEmbedder
      emb_dim: 512
    encoder: !BiLSTMSeqTransducer
      layers: 1
    mlp: !MLP
      hidden_dim: 512
      activation: 'tanh'
  train: !SimpleTrainingRegimen
    batcher: !SrcBatcher
      batch_size: 32
    trainer: !AdamTrainer
      alpha: 0.001
    run_for_epochs: 20
    src_file: examples/data/head.en
    trg_file: examples/data/head.smallids
    dev_tasks:
      - !LossEvalTask
        src_file: examples/data/head.en
        ref_file: examples/data/head.smallids
      - !AccuracyEvalTask
        eval_metrics: accuracy
        src_file: examples/data/head.en
        ref_file: examples/data/head.smallids
        hyp_file: examples/output/{EXP}.test_hyp
