defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: recall|nbest=1,recall|nbest=5
  train:
    batch_strategy: shuffle
    trainer: adam
    learning_rate: 0.001 
    dropout: 0.0
    dev_metrics: recall|nbest=1,recall|nbest=5
    training_corpus: !BilingualTrainingCorpus
      train_src: examples/data/train-char.ja
      train_trg: examples/data/train.allids
      train_id_file: examples/data/train.allids
      dev_src: examples/data/dev-char.ja
      dev_trg: examples/data/dev.allids
      dev_id_file: examples/data/dev.allids
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !IDReader {}
    model: !DotProductRetriever
      src_embedder: !SimpleWordEmbedder
        emb_dim: 32
        vocab_size: 20000
      src_encoder: !SegmentingEncoder
        lmbd_learning:
          initial: 0.1
          warmup: 0
          grow: 2
          max: 1.0
          min: 0 
        embed_encoder: !LSTMEncoder
          input_dim: 32
          hidden_dim: 32
          layers: 1
          bidirectional: true
        segment_transducer: !SegmentTransducer
          encoder: !LSTMEncoder
            input_dim: 32
            hidden_dim: 32
            bidirectional: false
            layers: 1
#          encoder: !IdentityEncoder {}
#          transformer: !CategorySegmentTransformer
#            input_dim: 32
#            category_dim: 40
#            embed_dim: 32
          transformer: !TailSegmentTransformer {}
#          transformer: !AverageSegmentTransformer {}
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 32
        vocab_size: 20000
      trg_encoder: !LSTMEncoder
        input_dim: 32
        hidden_dim: 32
        layers: 1
      database: !StandardRetrievalDatabase
        reader: !PlainTextReader {}
        database_file: examples/data/traindevtest.en
  decode:
    src_file: examples/data/test-char.ja
    report_path: examples/output/<EXP>.report
    candidate_id_file: examples/data/test.allids
  evaluate:
    ref_file: examples/data/test.allids

segmenting0.1:
  train:
     dropout: 0.0
